//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.WebFormApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        CZBK.ItcastOA.WebFormApp.ServiceReference1.HelloWorldResponse HelloWorld(CZBK.ItcastOA.WebFormApp.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<CZBK.ItcastOA.WebFormApp.ServiceReference1.HelloWorldResponse> HelloWorldAsync(CZBK.ItcastOA.WebFormApp.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        int Add(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int a, int b);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 LoadUserInfoListResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadUserInfoList", ReplyAction="*")]
        CZBK.ItcastOA.WebFormApp.ServiceReference1.LoadUserInfoListResponse LoadUserInfoList(CZBK.ItcastOA.WebFormApp.ServiceReference1.LoadUserInfoListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadUserInfoList", ReplyAction="*")]
        System.Threading.Tasks.Task<CZBK.ItcastOA.WebFormApp.ServiceReference1.LoadUserInfoListResponse> LoadUserInfoListAsync(CZBK.ItcastOA.WebFormApp.ServiceReference1.LoadUserInfoListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public CZBK.ItcastOA.WebFormApp.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(CZBK.ItcastOA.WebFormApp.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public CZBK.ItcastOA.WebFormApp.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(CZBK.ItcastOA.WebFormApp.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadUserInfoListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadUserInfoList", Namespace="http://tempuri.org/", Order=0)]
        public CZBK.ItcastOA.WebFormApp.ServiceReference1.LoadUserInfoListRequestBody Body;
        
        public LoadUserInfoListRequest() {
        }
        
        public LoadUserInfoListRequest(CZBK.ItcastOA.WebFormApp.ServiceReference1.LoadUserInfoListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LoadUserInfoListRequestBody {
        
        public LoadUserInfoListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadUserInfoListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadUserInfoListResponse", Namespace="http://tempuri.org/", Order=0)]
        public CZBK.ItcastOA.WebFormApp.ServiceReference1.LoadUserInfoListResponseBody Body;
        
        public LoadUserInfoListResponse() {
        }
        
        public LoadUserInfoListResponse(CZBK.ItcastOA.WebFormApp.ServiceReference1.LoadUserInfoListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadUserInfoListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoadUserInfoListResult;
        
        public LoadUserInfoListResponseBody() {
        }
        
        public LoadUserInfoListResponseBody(string LoadUserInfoListResult) {
            this.LoadUserInfoListResult = LoadUserInfoListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : CZBK.ItcastOA.WebFormApp.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<CZBK.ItcastOA.WebFormApp.ServiceReference1.WebService1Soap>, CZBK.ItcastOA.WebFormApp.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CZBK.ItcastOA.WebFormApp.ServiceReference1.HelloWorldResponse CZBK.ItcastOA.WebFormApp.ServiceReference1.WebService1Soap.HelloWorld(CZBK.ItcastOA.WebFormApp.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            CZBK.ItcastOA.WebFormApp.ServiceReference1.HelloWorldRequest inValue = new CZBK.ItcastOA.WebFormApp.ServiceReference1.HelloWorldRequest();
            inValue.Body = new CZBK.ItcastOA.WebFormApp.ServiceReference1.HelloWorldRequestBody();
            CZBK.ItcastOA.WebFormApp.ServiceReference1.HelloWorldResponse retVal = ((CZBK.ItcastOA.WebFormApp.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CZBK.ItcastOA.WebFormApp.ServiceReference1.HelloWorldResponse> CZBK.ItcastOA.WebFormApp.ServiceReference1.WebService1Soap.HelloWorldAsync(CZBK.ItcastOA.WebFormApp.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<CZBK.ItcastOA.WebFormApp.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            CZBK.ItcastOA.WebFormApp.ServiceReference1.HelloWorldRequest inValue = new CZBK.ItcastOA.WebFormApp.ServiceReference1.HelloWorldRequest();
            inValue.Body = new CZBK.ItcastOA.WebFormApp.ServiceReference1.HelloWorldRequestBody();
            return ((CZBK.ItcastOA.WebFormApp.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Add(int a, int b) {
            return base.Channel.Add(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int a, int b) {
            return base.Channel.AddAsync(a, b);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CZBK.ItcastOA.WebFormApp.ServiceReference1.LoadUserInfoListResponse CZBK.ItcastOA.WebFormApp.ServiceReference1.WebService1Soap.LoadUserInfoList(CZBK.ItcastOA.WebFormApp.ServiceReference1.LoadUserInfoListRequest request) {
            return base.Channel.LoadUserInfoList(request);
        }
        
        public string LoadUserInfoList() {
            CZBK.ItcastOA.WebFormApp.ServiceReference1.LoadUserInfoListRequest inValue = new CZBK.ItcastOA.WebFormApp.ServiceReference1.LoadUserInfoListRequest();
            inValue.Body = new CZBK.ItcastOA.WebFormApp.ServiceReference1.LoadUserInfoListRequestBody();
            CZBK.ItcastOA.WebFormApp.ServiceReference1.LoadUserInfoListResponse retVal = ((CZBK.ItcastOA.WebFormApp.ServiceReference1.WebService1Soap)(this)).LoadUserInfoList(inValue);
            return retVal.Body.LoadUserInfoListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CZBK.ItcastOA.WebFormApp.ServiceReference1.LoadUserInfoListResponse> CZBK.ItcastOA.WebFormApp.ServiceReference1.WebService1Soap.LoadUserInfoListAsync(CZBK.ItcastOA.WebFormApp.ServiceReference1.LoadUserInfoListRequest request) {
            return base.Channel.LoadUserInfoListAsync(request);
        }
        
        public System.Threading.Tasks.Task<CZBK.ItcastOA.WebFormApp.ServiceReference1.LoadUserInfoListResponse> LoadUserInfoListAsync() {
            CZBK.ItcastOA.WebFormApp.ServiceReference1.LoadUserInfoListRequest inValue = new CZBK.ItcastOA.WebFormApp.ServiceReference1.LoadUserInfoListRequest();
            inValue.Body = new CZBK.ItcastOA.WebFormApp.ServiceReference1.LoadUserInfoListRequestBody();
            return ((CZBK.ItcastOA.WebFormApp.ServiceReference1.WebService1Soap)(this)).LoadUserInfoListAsync(inValue);
        }
    }
}
